########
#
#    PRODUCTION ENVIRONMENT SETTINGS
#
########

server.port=8080

spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
spring.http.encoding.force-response=true

management.server.port=80
management.server.ssl.enabled=false
management.health.pubsub.enabled=false

logging.file=look-see.log

#####################################
# NEO4J SPRING DATA
#####################################
#spring.data.neo4j.uri=NEO4J_BOLT_URI
#spring.data.neo4j.username=NEO4J_USERNAME
#spring.data.neo4j.password=NEO4J PASSWORD
#spring.data.neo4j.database=NEO4J_DATABASE_NAME

logging.level.org.springframework.data.neo4j=WARN

#Google cloud credentials
#spring.cloud.gcp.credentials.location=GCP_CREDENTIALS_LOCATION

########
#  GCP Pub/Sub
########

#spring.cloud.gcp.project-id=PROJECT_ID
#pubsub.error_topic=AUDIT_ERROR_TOPIC
#pubsub.audit_update=AUDIT_UPDATE_TOPIC
#pubsub.page_audit_topic=PAGE_AUDIT_TOPIC

# Default values for local development and testing
spring.cloud.gcp.project-id=test-project
pubsub.page_audit_topic=page-audit-topic
pubsub.audit_update=audit-update-topic
pubsub.error_topic=audit-error-topic

logging.level.org.springframework.beans=WARN
logging.level.com.looksee=WARN
